# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SUNXI_BOARD) += board.dtb
dtb-$(CONFIG_ARCH_SUNXI) += \
	sun20i-d1-licheerv-86panel.dtb \
	sun20i-d1-licheerv-86panel-720x720.dtb \
	sun20i-d1-licheerv-dock.dtb \
	sun20i-d1-licheerv-dock-480x272.dtb \
	sun20i-d1-licheerv-dock-800x480.dtb \
	sun20i-d1-licheerv-dock-1024x600.dtb \
	sun20i-d1-licheerv-dock-mipi.dtb \
	sun20i-d1-nezha.dtb \
	sun20i-d1-nezha-lcd.dtb \
	sun20i-d1-nezha-min.dtb
