dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-MM-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-MM-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-MM-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-synology-DS418.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-synology-DS418j.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
