# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_RK_CAMERA_MODULE) += rk_camera_module.o

obj-$(CONFIG_VIDEO_ADV_CAMERA_MODULE) += adv_camera_module.o
obj-$(CONFIG_VIDEO_APTINA_CAMERA_MODULE) += aptina_camera_module.o
obj-$(CONFIG_VIDEO_IMX_CAMERA_MODULE) += imx_camera_module.o
obj-$(CONFIG_VIDEO_OV_CAMERA_MODULE) += ov_camera_module.o
obj-$(CONFIG_VIDEO_SC_CAMERA_MODULE) += sc_camera_module.o
obj-$(CONFIG_VIDEO_TC_CAMERA_MODULE) += tc_camera_module.o

obj-$(CONFIG_VIDEO_OV8858) += ov8858_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV2710) += ov2710_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV4689) += ov4689_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_IMX323) += imx323_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV7750) += ov7750_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_TC358749XBG) += tc358749xbg_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_ADV7181) += adv7181_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV7675) += ov7675_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_NT99230) += nt99230_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV13850) += ov13850_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV9281) += ov9281_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV9750) += ov9750_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_OV5640) += ov5640_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_SC031GS) += sc031gs_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_SC2232) += sc2232_v4l2-i2c-subdev.o
obj-$(CONFIG_VIDEO_ISL79987) += isl79987_v4l2-i2c-subdev.o
